"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=^fc%^jg!wj6&6t=ywq&ncd7)#4shjtu#i0#flm19g_(@u$x_h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# Tell Django to use your custom user model
AUTH_USER_MODEL ='bookshelf.CustomUser'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   'bookshelf'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = 'list_books'
LOGOUT_REDIRECT_URL = '/login/'    
SIGNUP_REDIRECT_URL = 'login' 
LOGIN_REDIRECT_URL = '/redirect/'  # This path maps to the redirect_based_on_role view
LOGIN_URL = '/books/'


# # Security changes for this project
# SECURE_BROWSER_XSS_FILTER = True
# X_FRAME_OPTIONS = 'DENY'
# SECURE_CONTENT_TYPE_NOSNIFF = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = False

# ===============================
# Django Security Settings for HTTPS and Secure Web Communication
# ===============================

# 1. Redirect all HTTP requests to HTTPS
# This forces browsers to use HTTPS, improving security by encrypting data in transit.
# WARNING: Set to True only when you have SSL/TLS correctly configured in production!
SECURE_SSL_REDIRECT = False  # Redirect HTTP -> HTTPS

# 2. HTTP Strict Transport Security (HSTS) settings
# Instruct browsers to only access the site via HTTPS for the specified period (in seconds).
# 31536000 seconds = 1 year, recommended for production.
SECURE_HSTS_SECONDS = 31536000

# Include all subdomains in the HSTS policy. Recommended for comprehensive HTTPS enforcement.
SECURE_HSTS_INCLUDE_SUBDOMAINS = False


# Allows your domain to be included in browsers' preloaded HSTS lists.
# This means browsers will know your site is HTTPS only even before first visit.
SECURE_HSTS_PRELOAD = True

# 3. Cookies security
# Ensure session cookies are only sent over HTTPS connections to prevent interception.
SESSION_COOKIE_SECURE = False

# Ensure CSRF cookies are only sent over HTTPS, protecting against cross-site request forgery.
CSRF_COOKIE_SECURE = False

# 4. HTTP Security Headers

# Prevent your site from being embedded in frames/iframes to avoid clickjacking attacks.
X_FRAME_OPTIONS = 'DENY'

# Prevent browsers from MIME-sniffing a response away from the declared content-type.
# Helps avoid certain types of attacks based on content-type confusion.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable the browser's built-in Cross-Site Scripting (XSS) filter and block detected attacks.
SECURE_BROWSER_XSS_FILTER = True

# 5. Additional recommendations (optional but good practice)

# Set a Content Security Policy (CSP) to restrict the sources of content (scripts, images, styles, etc.)
# You can configure django-csp or add custom middleware for this.
# Example:
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'", "trusted-scripts.example.com")

# ===============================
# Important Notes:
# - These settings should be enabled in your **production environment only**, where HTTPS is properly set up.
# - During development (local testing), it's common to set SECURE_SSL_REDIRECT = False
#   and disable cookie security flags to avoid issues without HTTPS.
#
# Example to differentiate dev and prod settings:
#
# import os
# DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'
#
# if not DEBUG:
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
# else:
#     SECURE_SSL_REDIRECT = False
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False
#     SECURE_HSTS_SECONDS = 0
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = False
#     SECURE_HSTS_PRELOAD = False
#
# ===============================

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
